<a href="https://colab.research.google.com/github/ZohebAbai/Deep-Learning-Projects/blob/master/Tensorflow_Keras/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundaments

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.7.0


## Tensors

TensorFlow, as the name indicates, is a framework to define and run computations involving tensors. A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes. TensorFlow programs work by first building a graph of tf.Tensor objects, detailing how each tensor is computed based on the other available tensors and then by running parts of this graph to achieve the desired results. 

### tf.constant (immutable)


In [2]:
scalar = tf.constant(9)
print(f"Tensor value: {scalar} of rank {scalar.ndim}")

Tensor value: 9 of rank 0


In [3]:
vector = tf.constant([10,7])
print(f"Tensor value: {vector} of rank {vector.ndim}")

Tensor value: [10  7] of rank 1


In [4]:
matrix = tf.constant([[10,7],
                      [7,10]])
print(f"Tensor value:\n {matrix} of rank {matrix.ndim}")

Tensor value:
 [[10  7]
 [ 7 10]] of rank 2


In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]], dtype=tf.float16)
print(f"Tensor value:\n {tensor} of rank {tensor.ndim}")

Tensor value:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]] of rank 3


### tf.Variable (mutable)

In [6]:
mutable_tensor = tf.Variable([10,7])
mutable_tensor[0].assign(7)
print(f"Tensor value:\n {mutable_tensor}")

Tensor value:
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


In [7]:
D = tf.cast(mutable_tensor, tf.float16)
print(f"Changed the type from {mutable_tensor.dtype} to {D.dtype}")

Changed the type from <dtype: 'int32'> to <dtype: 'float16'>


## Compatibility with Numpy

In [8]:
arr = np.arange(1,25, dtype=np.int32)
a = tf.constant(arr, shape=(2,3,4))
print(a)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [9]:
# Get various attributes of tensor
print("Datatype of every element:", a.dtype)
print("Number of dimensions (rank):", a.ndim)
print("Shape of tensor:", a.shape)
print("Total number of elements:", tf.size(a).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 3
Shape of tensor: (2, 3, 4)
Total number of elements: 24


In [10]:
print(f"Elements along last axis of tensor:\n {a[:,:,-1]}")

Elements along last axis of tensor:
 [[ 4  8 12]
 [16 20 24]]


In [11]:
tf.expand_dims(a, axis=-1)

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15],
         [16]],

        [[17],
         [18],
         [19],
         [20]],

        [[21],
         [22],
         [23],
         [24]]]], dtype=int32)>

In [12]:
tf.squeeze(a)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Random Tensor Generators

In [13]:
rand1 = tf.random.normal((3,2), seed=101)
rand2 = tf.random.normal((3,2), seed=202)
rand1 == rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [14]:
rand3 = tf.random.uniform((3,4), seed=101)
rand3_s = tf.random.shuffle(rand3, seed=101)
print(rand3, rand3_s)

tf.Tensor(
[[0.06821764 0.7445649  0.63443744 0.8038496 ]
 [0.203704   0.8928938  0.30328155 0.44761705]
 [0.70831895 0.66599715 0.02255964 0.85973096]], shape=(3, 4), dtype=float32) tf.Tensor(
[[0.70831895 0.66599715 0.02255964 0.85973096]
 [0.06821764 0.7445649  0.63443744 0.8038496 ]
 [0.203704   0.8928938  0.30328155 0.44761705]], shape=(3, 4), dtype=float32)


In [15]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [16]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## Basic Operations

In [17]:
rand1 + 25

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[22.684002, 24.92088 ],
       [24.100128, 25.316645],
       [23.8881  , 26.394938]], dtype=float32)>

In [18]:
rand1 -10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-12.315997 , -10.079122 ],
       [-10.899872 ,  -9.683355 ],
       [-11.1119   ,  -8.6050625]], dtype=float32)>

In [19]:
tf.matmul(rand1, tf.transpose(rand2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.405108  ,  0.63510007, -0.7041137 ],
       [ 1.4321251 ,  0.41159612, -0.6258149 ],
       [ 3.207335  ,  0.9848113 , -1.7909584 ]], dtype=float32)>

In [20]:
tf.tensordot(rand1, tf.transpose(rand2), axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.405108  ,  0.63510007, -0.7041137 ],
       [ 1.4321251 ,  0.41159612, -0.6258149 ],
       [ 3.207335  ,  0.9848113 , -1.7909584 ]], dtype=float32)>

In [21]:
tf.reduce_mean(rand2).numpy()

-0.024359882

In [22]:
tf.math.reduce_std(rand2).numpy()

0.88348025

In [23]:
tf.square(tf.range(1,5))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [24]:
tf.one_hot([0,1,2], depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>